#!/usr/bin/env python3
"""Generate the Mermaid diagram (into README.md) and the schemdraw SVG
from wiring.py. Run via tools/gen-schematic.sh."""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)

from wiring import NODES, EDGES, ROLE_STYLE, PARTS  # noqa: E402

README = os.path.join(REPO, "README.md")
SVG = os.path.join(REPO, "images", "hobd_uni_schematic.svg")
FULL_SVG = os.path.join(REPO, "images", "hobd_uni_full_schematic.svg")
START = "<!-- SCHEMATIC:MERMAID:START (generated by tools/gen-schematic.sh, do not edit) -->"
END = "<!-- SCHEMATIC:MERMAID:END -->"


# ---------------------------------------------------------------- Mermaid
def mermaid() -> str:
    arrow = {"solid": "-->", "dashed": "-.->", "bidir": "<-->"}
    out = ["flowchart TB"]
    for nid, (label, role) in NODES.items():
        out.append(f'  {nid}["{label.replace(chr(10), "<br/>")}"]:::{role}')
    out.append("")
    for src, dst, label, style in EDGES:
        a = arrow[style]
        out.append(f'  {src} {a}|"{label}"| {dst}' if label else f"  {src} {a} {dst}")
    out.append("")
    for role, style in ROLE_STYLE.items():
        out.append(f"  classDef {role} {style};")
    return "\n".join(out)


def inject_readme() -> None:
    block = f"{START}\n```mermaid\n{mermaid()}\n```\n{END}"
    with open(README, encoding="utf-8") as f:
        text = f.read()
    if START in text and END in text:
        text = re.sub(re.escape(START) + r".*?" + re.escape(END), block, text, flags=re.S)
    else:
        raise SystemExit(f"markers not found in {README}; add {START} / {END} around the diagram")
    with open(README, "w", encoding="utf-8") as f:
        f.write(text)
    print("updated README Mermaid block")


# ---------------------------------------------------------------- schemdraw
def schematic() -> None:
    import schemdraw
    schemdraw.use("svg")
    import schemdraw.elements as elm

    P = PARTS
    Schottky = getattr(elm, "Schottky", elm.Diode)
    Zener = getattr(elm, "Zener", getattr(elm, "DiodeZener", elm.Diode))
    Fuse = getattr(elm, "Fuse", elm.Resistor)

    d = schemdraw.Drawing()
    d.config(unit=2.0, fontsize=12)

    def heading(txt, x, y):
        d.here = (x, y)
        d.add(elm.Label().label(txt, loc="right").color("#888"))

    # 1) power protection chain
    heading("POWER PROTECTION", 0, 0.9)
    d.here = (0, 0)
    d += elm.Dot(open=True).label("+12V DLC", "left")
    d += Fuse().right().label(P["fuse"])
    d += Schottky().right().label(P["diode"])
    nA = d.add(elm.Dot())
    d += elm.Line().right().length(1.2)
    nB = d.add(elm.Dot())
    d += elm.Line().right().length(1.6)
    d += elm.Dot(open=True).label("Vin", "right")
    d += Zener().down().at(nA.center).label(P["tvs"], loc="left")
    d += elm.Ground()
    d += elm.Capacitor().down().at(nB.center).label(P["bulk"], loc="right")
    d += elm.Ground()

    # 2) ESP / HC-05 level shifter (5V -> 3.3V resistor divider)
    heading("LEVEL SHIFT  5V -> 3.3V", 0, -2.7)
    d.here = (0, -3.6)
    d += elm.Dot(open=True).label("UNO TX (D1/D11)", "left")
    d += elm.Resistor().right().label(P["lvl_top"])
    nB = d.add(elm.Dot())
    d += elm.Line().right().length(1.6)
    d += elm.Dot(open=True).label("3.3V  ESP/HC-05 RX", "right")
    d += elm.Resistor().down().at(nB.center).label(P["lvl_bot"], loc="bottom", ofst=0.3)
    d += elm.Ground()

    # 3) battery voltage divider into the ADC
    heading("BATTERY SENSE DIVIDER", 0, -6.3)
    d.here = (0, -7.2)
    d += elm.Dot(open=True).label("+12V batt", "left")
    d += elm.Resistor().right().label(P["div_top"])
    nC = d.add(elm.Dot())
    d += elm.Line().right().length(1.2)
    nD = d.add(elm.Dot())
    d += elm.Line().right().length(1.6)
    d += elm.Dot(open=True).label("A0", "right")
    d += elm.Resistor().down().at(nC.center).label(P["div_bot"], loc="left")
    d += elm.Ground()
    d += elm.Capacitor().down().at(nD.center).label(P["div_cap"], loc="right")
    d += elm.Ground()

    # 4) K-line interface
    heading("K-LINE INTERFACE", 0, -9.9)
    d.here = (0, -10.8)
    d += elm.Dot(open=True).label("DLC K-line ~12V", "left")
    d += elm.Resistor().right().label(P["kline_series"])
    Box = getattr(elm, "RBox", elm.Resistor)
    d += Box().right().label(P["kline_xcvr"])
    d += elm.Line().right().length(0.6)
    d += elm.Dot(open=True).label("UNO D12", "right")

    os.makedirs(os.path.dirname(SVG), exist_ok=True)
    d.save(SVG)
    print(f"wrote {os.path.relpath(SVG, REPO)}")


def full_schematic() -> None:
    """Complete build schematic: UNO + every module + protection, one image."""
    import schemdraw
    schemdraw.use("svg")
    import schemdraw.elements as elm

    P = PARTS
    Schottky = getattr(elm, "Schottky", elm.Diode)
    Zener = getattr(elm, "Zener", getattr(elm, "DiodeZener", elm.Diode))
    Fuse = getattr(elm, "Fuse", elm.Resistor)

    def ic(label, left=(), right=(), w=2.0, h=None):
        pins = [elm.IcPin(name=n, side="left", anchorname=a) for a, n in left]
        pins += [elm.IcPin(name=n, side="right", anchorname=a) for a, n in right]
        rows = max(len(left), len(right), 1)
        return elm.Ic(pins=pins, size=(w, h or (rows + 1) * 0.9),
                      label=label, plblsize=12, leadlen=0.6)

    d = schemdraw.Drawing()
    d.config(unit=1.5, fontsize=11)

    def gnd(at):
        d.add(elm.Ground().at(at))

    def v5(at):
        d.add(elm.Vdd().at(at).label("+5V", fontsize=9))

    # ---- central Arduino UNO ----
    uno = elm.Ic(
        pins=[
            elm.IcPin(name="Vin", side="left", anchorname="Vin"),
            elm.IcPin(name="5V", side="left", anchorname="V5"),
            elm.IcPin(name="GND", side="left", anchorname="GND"),
            elm.IcPin(name="RESET", side="left", anchorname="RST"),
            elm.IcPin(name="D13", side="right", anchorname="D13"),
            elm.IcPin(name="D12", side="right", anchorname="D12"),
            elm.IcPin(name="D11", side="right", anchorname="D11"),
            elm.IcPin(name="D10", side="right", anchorname="D10"),
            elm.IcPin(name="D1 TX", side="right", anchorname="D1"),
            elm.IcPin(name="A0", side="bottom", anchorname="A0"),
            elm.IcPin(name="A1", side="bottom", anchorname="A1"),
            elm.IcPin(name="A2", side="bottom", anchorname="A2"),
            elm.IcPin(name="A3", side="bottom", anchorname="A3"),
            elm.IcPin(name="A4 SDA", side="bottom", anchorname="A4"),
            elm.IcPin(name="A5 SCL", side="bottom", anchorname="A5"),
        ],
        size=(6, 8), label="Arduino UNO", plblsize=15, leadlen=0.9,
    ).at((0, 0))
    d += uno
    v5(uno.V5)
    gnd(uno.GND)

    # ======================= POWER (left) =======================
    dlc = ic("",
             right=[("V12", "+12V"), ("GND", "GND"), ("KL", "K-line")],
             w=2.2).at((-13, 1.5)).anchor("center")
    d += dlc
    d.add(elm.Label().at((-13, 3.8)).label("Honda DLC", fontsize=11))
    d += elm.Line().right(0.6).at(dlc.V12)
    d += Fuse().right().label(P["fuse"], fontsize=9)
    d += Schottky().right().label(P["diode"], fontsize=9)
    nprot = d.add(elm.Dot())
    d += Zener().down().at(nprot.center).label(P["tvs"], loc="left", fontsize=8)
    gnd(d.here)
    d += elm.Capacitor().down().at((nprot.center[0] + 1.3, nprot.center[1])).label(P["bulk"], loc="right", fontsize=8)
    gnd(d.here)
    d += elm.Line().at((nprot.center[0] + 1.3, nprot.center[1])).to(nprot.center)
    d += elm.Wire("-|").at(nprot.center).to(uno.Vin).label("+12V prot", loc="top", fontsize=8)
    gnd(dlc.GND)

    # mark the DLC K-line pin as the source of that net (the K-line interface
    # lives next to the transceiver on the right, not wired across the page)
    d += elm.Line().right(0.5).at(dlc.KL)
    d += elm.Dot(open=True).label("to K-line\ninterface", "right", fontsize=8)

    # ======================= COMMS (right, well spaced) =======================
    espx = 11
    esp = ic("", left=[("V5", "5V"), ("G", "GND"), ("RX", "RX2")], w=2.8).at((espx, 7)).anchor("center")
    d += esp
    d.add(elm.Label().at((espx, 9.2)).label("ESP32  (WiFi AP, WS :81)", fontsize=10))
    v5(esp.V5)
    gnd(esp.G)
    d += elm.Line().right(0.8).at(uno.D1)
    d += elm.Resistor().right().label(P["lvl_top"], fontsize=8)
    nlv = d.add(elm.Dot())
    d += elm.Resistor().down().at(nlv.center).label(P["lvl_bot"], loc="right", fontsize=8)
    gnd(d.here)
    d += elm.Wire("-|").at(nlv.center).to(esp.RX).label("3.3V", loc="top", fontsize=8)

    hc = ic("", left=[("RXD", "RXD"), ("TXD", "TXD"), ("VCC", "VCC"), ("G", "GND")], w=2.6).at((espx, -1)).anchor("center")
    d += hc
    d.add(elm.Label().at((espx, 1.8)).label("HC-05 Bluetooth", fontsize=10))
    v5(hc.VCC)
    gnd(hc.G)
    d += elm.Line().right(0.8).at(uno.D11)
    d += elm.Resistor().right().label(P["lvl_top"], fontsize=8)
    nlv2 = d.add(elm.Dot())
    d += elm.Resistor().down().at(nlv2.center).label(P["lvl_bot"], loc="right", fontsize=8)
    gnd(d.here)
    d += elm.Wire("-|").at(nlv2.center).to(hc.RXD).label("3.3V", loc="top", fontsize=8)
    d += elm.Wire("-|").at(hc.TXD).to(uno.D10)

    # K-line transceiver (right); its own K-line terminal sits beside it
    kx = ic("", left=[("RX", "RX"), ("TX", "TX"), ("VCC", "VCC"), ("G", "GND")],
            right=[("K", "K"), ("VB", "VB")], w=2.6).at((espx, -9)).anchor("center")
    d += kx
    d.add(elm.Label().at((espx, -6.4)).label("L9637D K-line xcvr", fontsize=10))
    v5(kx.VCC)
    gnd(kx.G)
    d += elm.Wire("-|").at(kx.RX).to(uno.D12)
    d += elm.Wire("-|").at(kx.TX).to(uno.D12)
    d += elm.Line().right(0.4).at(kx.K)
    d += elm.Resistor().right().label(P["kline_series"], fontsize=8)
    d += elm.Dot(open=True).label("K-line\n(Honda DLC)", "right", fontsize=8)
    d += elm.Line().right(0.5).at(kx.VB)
    d += elm.Dot(open=True).label("+12V prot", "right", fontsize=8)

    # buzzer on D13 (open gap between the UNO and the modules)
    d += elm.Line().right(2.5).at(uno.D13)
    d += elm.Speaker().right().label(f"buzzer\n{P['buzzer']}", fontsize=8)
    gnd(d.here)

    # ======================= I/O (bottom) =======================
    d += elm.Line().down(0.8).at(uno.A0)
    nA0 = d.add(elm.Dot())
    d += elm.Resistor().down().at(nA0.center).label(P["div_bot"], loc="right", fontsize=8)
    gnd(d.here)
    d += elm.Resistor().left().at(nA0.center).label(P["div_top"], fontsize=8)
    d += elm.Vdd().label("+12V batt", fontsize=8)

    d += elm.Line().down(1.6).at(uno.A1)
    d += elm.Dot(open=True).label("AEM AFR\n0-5V", "bottom", fontsize=8)
    d += elm.Line().down(2.4).at(uno.A2)
    d += elm.Dot(open=True).label("Fuel press\n0.5-4.5V", "bottom", fontsize=8)

    d += elm.Line().down(3.2).at(uno.A3)
    d += elm.Button().down().label(P["nav_btn"], loc="left", fontsize=8)
    gnd(d.here)

    d += elm.Line().left(0.9).at(uno.RST)
    d += elm.Button().down().label(f"reset {P['reset_btn']}", loc="left", fontsize=8)
    gnd(d.here)

    # LCD on A4/A5
    lcd = ic("I2C LCD 16x2",
             left=[("SDA", "SDA"), ("SCL", "SCL"), ("VCC", "VCC"), ("G", "GND")], w=3).at((1, -12)).anchor("center")
    d += lcd
    v5(lcd.VCC)
    gnd(lcd.G)
    d += elm.Wire("-|").at(lcd.SDA).to(uno.A4).label(P["i2c_pull"] + " pull-ups to +5V", loc="bottom", fontsize=8)
    d += elm.Wire("-|").at(lcd.SCL).to(uno.A5)

    os.makedirs(os.path.dirname(FULL_SVG), exist_ok=True)
    d.save(FULL_SVG)
    print(f"wrote {os.path.relpath(FULL_SVG, REPO)}")


if __name__ == "__main__":
    inject_readme()
    schematic()
    full_schematic()
