#!/usr/bin/env python3
"""Generate the Mermaid diagram (into README.md) and the schemdraw SVG
from wiring.py. Run via tools/gen-schematic.sh."""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)

from wiring import NODES, EDGES, ROLE_STYLE, PARTS  # noqa: E402

README = os.path.join(REPO, "README.md")
SVG = os.path.join(REPO, "images", "hobd_uni_schematic.svg")
START = "<!-- SCHEMATIC:MERMAID:START (generated by tools/gen-schematic.sh, do not edit) -->"
END = "<!-- SCHEMATIC:MERMAID:END -->"


# ---------------------------------------------------------------- Mermaid
def mermaid() -> str:
    arrow = {"solid": "-->", "dashed": "-.->", "bidir": "<-->"}
    out = ["flowchart TB"]
    for nid, (label, role) in NODES.items():
        out.append(f'  {nid}["{label.replace(chr(10), "<br/>")}"]:::{role}')
    out.append("")
    for src, dst, label, style in EDGES:
        a = arrow[style]
        out.append(f'  {src} {a}|"{label}"| {dst}' if label else f"  {src} {a} {dst}")
    out.append("")
    for role, style in ROLE_STYLE.items():
        out.append(f"  classDef {role} {style};")
    return "\n".join(out)


def inject_readme() -> None:
    block = f"{START}\n```mermaid\n{mermaid()}\n```\n{END}"
    with open(README, encoding="utf-8") as f:
        text = f.read()
    if START in text and END in text:
        text = re.sub(re.escape(START) + r".*?" + re.escape(END), block, text, flags=re.S)
    else:
        raise SystemExit(f"markers not found in {README}; add {START} / {END} around the diagram")
    with open(README, "w", encoding="utf-8") as f:
        f.write(text)
    print("updated README Mermaid block")


# ---------------------------------------------------------------- schemdraw
def schematic() -> None:
    import schemdraw
    schemdraw.use("svg")
    import schemdraw.elements as elm

    P = PARTS
    Schottky = getattr(elm, "Schottky", elm.Diode)
    Zener = getattr(elm, "Zener", getattr(elm, "DiodeZener", elm.Diode))
    Fuse = getattr(elm, "Fuse", elm.Resistor)

    d = schemdraw.Drawing()
    d.config(unit=2.0, fontsize=12)

    def heading(txt, x, y):
        d.here = (x, y)
        d.add(elm.Label().label(txt, loc="right").color("#888"))

    # 1) power protection chain
    heading("POWER PROTECTION", 0, 0.9)
    d.here = (0, 0)
    d += elm.Dot(open=True).label("+12V DLC", "left")
    d += Fuse().right().label(P["fuse"])
    d += Schottky().right().label(P["diode"])
    nA = d.add(elm.Dot())
    d += elm.Line().right().length(1.2)
    nB = d.add(elm.Dot())
    d += elm.Line().right().length(1.6)
    d += elm.Dot(open=True).label("Vin", "right")
    d += Zener().down().at(nA.center).label(P["tvs"], loc="left")
    d += elm.Ground()
    d += elm.Capacitor().down().at(nB.center).label(P["bulk"], loc="right")
    d += elm.Ground()

    # 2) ESP / HC-05 level shifter (5V -> 3.3V resistor divider)
    heading("LEVEL SHIFT  5V -> 3.3V", 0, -2.7)
    d.here = (0, -3.6)
    d += elm.Dot(open=True).label("UNO TX (D1/D11)", "left")
    d += elm.Resistor().right().label(P["lvl_top"])
    nB = d.add(elm.Dot())
    d += elm.Line().right().length(1.6)
    d += elm.Dot(open=True).label("3.3V  ESP/HC-05 RX", "right")
    d += elm.Resistor().down().at(nB.center).label(P["lvl_bot"], loc="bottom", ofst=0.3)
    d += elm.Ground()

    # 3) battery voltage divider into the ADC
    heading("BATTERY SENSE DIVIDER", 0, -6.3)
    d.here = (0, -7.2)
    d += elm.Dot(open=True).label("+12V batt", "left")
    d += elm.Resistor().right().label(P["div_top"])
    nC = d.add(elm.Dot())
    d += elm.Line().right().length(1.2)
    nD = d.add(elm.Dot())
    d += elm.Line().right().length(1.6)
    d += elm.Dot(open=True).label("A0", "right")
    d += elm.Resistor().down().at(nC.center).label(P["div_bot"], loc="left")
    d += elm.Ground()
    d += elm.Capacitor().down().at(nD.center).label(P["div_cap"], loc="right")
    d += elm.Ground()

    # 4) K-line interface
    heading("K-LINE INTERFACE", 0, -9.9)
    d.here = (0, -10.8)
    d += elm.Dot(open=True).label("DLC K-line ~12V", "left")
    d += elm.Resistor().right().label(P["kline_series"])
    Box = getattr(elm, "RBox", elm.Resistor)
    d += Box().right().label(P["kline_xcvr"])
    d += elm.Line().right().length(0.6)
    d += elm.Dot(open=True).label("UNO D12", "right")

    os.makedirs(os.path.dirname(SVG), exist_ok=True)
    d.save(SVG)
    print(f"wrote {os.path.relpath(SVG, REPO)}")


if __name__ == "__main__":
    inject_readme()
    schematic()
